-- crear base de datos dbCursos
CREATE DATABASE IF NOT EXISTS dbCurso
DEFAULT CHARACTER SET utf8;

-- poner en uso
USE dbCURSO;
SELECT DATABASE();
SHOW DATABASES;
-- Crear las tablas
CREATE TABLE PERSONA
(
DNIPER CHAR(8),
NOMPER VARCHAR(50),
APEPER VARCHAR(80),
FECNACPER DATE,
CELPER CHAR(9),
EMAPER VARCHAR(10),
SEXPER CHAR (1),
TIPPER CHAR (3),
DISTPER VARCHAR(80),
FECREGPER TIMESTAMP,
PWSPER VARCHAR (20),
CONSTRAINT DNIPER_PK PRIMARY KEY(DNIPER)
);
CREATE TABLE DEPARTAMENTO 
(
IDDEP INT,
NOMDEP VARCHAR (50),
DNIPER CHAR (8),
SALJEFDEP DECIMAL(8,2),
CONSTRAINT IDDEP_PK PRIMARY KEY (IDDEP)
);
-- CREAR UNA RELACION PERSONA DEPARTAMENTO
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PERSONA_DEPARTAMENTO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);